apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "data-entry-from.fullname" . }}-pvc
  labels:
    app: {{ include "data-entry-from.name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
