replicaCount: 1
#number of instances 
image:
  repository: 94233949/argo
  tag: v1.0.2
  pullPolicy: IfNotPresent

containerPort: 80 #The port number on which your application container listens for incoming requests. This port is used inside the container.

service:
  type: ClusterIP
  port: 80 #The port number on which the service will be exposed.

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# PersistentVolume (PV) and PersistentVolumeClaim (PVC) settings
persistence:
  enabled: true
  storageClass: "manual" # Use "default" if you have a default storage class
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  # Uncomment and configure the following if you need a specific path for the volume
  # path: /data
