apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-argo-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "my-argo-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

