{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: /mnt/data
{{- end }}

